#!/bin/sh
##commit doc_dir as git repo
commit_doc(){

  timestamp=$(date +%Y/%m/%d_%H:%M);
  : ${timestamp:=no comment};

  sh -ec "
    cd $DOC_DIR
    git add *
    git commit -m \"${*:-$timestamp}\"
  " || throw failed to commit
}
