#!/bin/sh
##commit doc_dir as git repo
commit_doc(){
  timestamp=`date +%Y/%m/%d_%H:%M`; : ${timestamp:=no comment};
  cd "$DOC_DIR" || throw commit_doc: cannot cd to $DOC_DIR
  git status > /dev/null 2> /dev/null || git init
  git add *; 
  git commit -m "${@:-$timestamp}";
}
