#!/bin/sh
kanban_edit(){ #<proj_name>
    set_dir "${1:?kanban_edit: specify project name with -k prjname!}";
    test "$1" = "-c" && { shift; commit_doc $@; exit; }
    TARGET_DATE=$(echo ${FORDATE:?FORDATE not defined});
    for i in todo doing done; do 
      TARGETS="$TARGETS ${TARGET_DATE}${i}.md"
      create_sln $i; 
    done
    nik_edit "${EDITOR_OPT:+$EDITOR_OPT -S $KANBAN_VIMRC_PATH}" "${TARGETS:-$@}"; 
}
