#!/bin/sh
##edit documents for specific condition
##command arguments will not be passed for this function directry
nik_edit(){
  target=
  if [ $# -eq 0 ]; then
    $EDITOR $EDITOR_OPT "$(get_doc_name)"
  else
    ## with args (e.g. -x, extreme mode), it opens all of document at the specified condition
    cd $DOC_DIR
    $EDITOR $EDITOR_OPT $@
  fi
  commit_doc
  unset target
}
