#!/bin/sh
##Date detection
set_date(){
test -z $1 && throw argumentNotSpecified $1;
NOW=$FORDATE
FORDATE=$1

if test ! -z "`echo "$FORDATE" | grep -E "\-|\+"`" ; then
  ##incremental description
  FORDATE="`echo $FORDATE | sed -r s/\./\ \&/g`"
  #target date
  TODATE="`expr $NOW $FORDATE`";

  #add 0 to the head for month with ONE digit
  test $FORMONTH -lt 10 && {
    TODATE="`echo $TODATE | sed -r s/\^/\&0/g`"
  }
  if test `expr $NOW / $TODATE` -gt 12; then
    throw dateInvalidException;
  else
    FORDATE=$TODATE;
  fi
elif test $FORDATE -gt 1231; then
  ## month larger than 12
  throw dateInvalidException;
elif test $FORDATE -lt 101; then
  ## month small than 1
  throw dateInvalidException;
else :;
fi
}
