#!/bin/sh
set_newest_doc(){
  DOC_NEWEST="$DOC_DIR/`nik_newest`"
  test -f "$DOC_NEWEST"
}
nik_newest(){
  nik_list --no-arrange | grep -E "[[:digit:]]{4}[[:alpha:]]" | sort -n | grep $ATTR | tail -1
}
