#!/bin/sh
# validate date and set it
set_date(){
  : ${1:?@nik/set_date: argument needed!}
  if 
    ! [ "$1" -ge 0 ] && ! [ "$1" -lt 0 ] 
  then
    throw argument must be a number
  elif 
    [ "$1" -le 101 ] || [ "$1" -gt 1231 ] 
  then
    throw argument range must be between 101 to 1231
  else
    date=$1
    [ $date -le 930 ] && date=0$date
    FORDATE=$date
    unset date
  fi
}
